# Generated by Django 5.0 on 2023-12-20 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0004_level_course_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='what_will_learn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storeapp.course')),
            ],
        ),
    ]
